### PR TITLE
Update to 2.2.0

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge/core A series of pull requests https://github.com/conda-forge/colored-feedstock/pull/7 https://github.com/conda-forge/colored-feedstock/pull/8 https://github.com/conda-forge/colored-feedstock/pull/9 https://github.com/conda-forge/colored-feedstock/pull/10 have been opened by the conda-forge bot but was not merged since June last year. I now fixed the most recent version and added myself as maintainer. Can one of you merge this pull request?

**Comment by mwcraig** [comment]
Thanks again, @jan-janssen

**Comment by jan-janssen** [comment]
@mwcraig Sure, I am always happy to help.

**Pull request merged**
